name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    # GitHub 서버가 아닌 내 윈도우 실행기에서 실행하도록 지정
    runs-on: self-hosted 
    
    steps:
      # 1. 리포지토리의 소스 코드를 실행기 폴더로 다운로드
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          clean: true

